#!/bin/sh
# labwc autostart -- launched once per session
# uConsole DSI-1 physically rotated; transform 90 = keyboard at bottom
wlr-randr --output DSI-1 --transform 270 2>/dev/null

swaybg -c '#101418' &
waybar &
mako &
nm-applet --indicator &
